FROM golang:alpine as builder

WORKDIR /app
COPY hello-world.go .

RUN GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o /app/hello-world .


FROM scratch

COPY --from=builder /app/hello-world .

ENTRYPOINT ["/hello-world"]